name: Release

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: yarn
      - run: npm ls axios
      - run: npm ls node-fetch
      - run: npm install -g pkg

      - name: Pack
        run: npm run pkgci

      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ env.RELEASE_VERSION }}
